### ISSUE TITLE
Add your pet's info

### ISSUE THREAD

**Issue by gabrysia694** [gabrysia694/MyPetSpotlight#1]
Hello,
any beginners are more than welcome to contribute to the project by adding their pet! :)

**Comment by Vishal-Parasram** [comment]
@gabrysia694 can I contribute.

**Comment by gabrysia694** [comment]
> @gabrysia694 can I contribute.

of course! Create a new PR with your code.

**Comment by Vishal-Parasram** [comment]
@gabrysia694 Added information. Review requested.

**Comment by Pragyan14** [comment]
I want to work on this issue please assign me this issue.

**Comment by AnkitAnandMastery17** [comment]
Can I work on this issue?

**Comment by gabrysia694** [comment]
> Can I work on this issue?

yes, please do. create a new PR with your code :)

**Comment by harisdev-netizen** [comment]
I'll make a new PR in a while @gabrysia694

**Comment by amike6** [comment]
hey would it be cool if i made a database that stores the pet info

**Comment by harisdev-netizen** [comment]
> hey would it be cool if i made a database that stores the pet info

That'd be great @amike6 , make an issue and ask the owner of the repository to assign you the issue.

**Comment by Bharadwajshivam28** [comment]
i want to add my pet info please let me @gabrysia694

**Comment by Gallantfarhan** [comment]
Can I work on this issue?

**Comment by gabrysia694** [comment]
> Can I work on this issue?

Of course! Fork the repository, add your pet’s info and create a PR

**Comment by Ruby-Jain** [comment]
Hi, Can I work on this issue?

**Comment by gabrysia694** [comment]
> Hi, Can I work on this issue?

Hello, of course. Add your pet's info and create a PR

**Comment by Ruby-Jain** [comment]
Hi,

Request you to please help me in running the project.
Please refer to the enclosed screenshot of the error for your reference.

<img width="1440" alt="Screenshot 2023-05-20 at 11 37 27 PM" src="https://github.com/gabrysia694/MyPetSpotlight/assets/74794352/f0917fce-4d3d-4c85-a7a2-bd11d71b2044">

**Comment by harisdev-netizen** [comment]
> 

Sure go ahead, create PR

**Comment by SyedTathahir** [comment]
I have created Pull request #64 please review it

**Comment by Helixjoe** [comment]
@gabrysia694 Kindly review my PR ( pet details added #65 )

**Comment by RaghavGoel01** [comment]
@gabrysia694 I have created pull request #66. Kindly review it

**Comment by venk404** [comment]
@gabrysia694 can I contribute.

**Comment by elidakirigo** [comment]
I'd like to contribute... and add my pet

**Comment by gabrysia694** [comment]
yes @venk404 and @elidakirigo, add your pet's info and create a PR :)

**Comment by Sakshikumari28** [comment]
I can contribute in this project ma'am please

**Comment by gabrysia694** [comment]
> I can contribute in this project ma'am please

of course, creat a new PR with your pet's info :)

**Comment by RuchirDixit** [comment]
Hey @gabrysia694, just created a new PR :  [](https://github.com/gabrysia694/MyPetSpotlight/pull/79)
 Request you to review and merge if found as expected :)
