### ISSUE TITLE
Add feature to upload pet photos

### ISSUE THREAD

**Issue by harisdev-netizen** [gabrysia694/MyPetSpotlight#10]
Currently, users can only enter text descriptions of their pets in **MyPetSpotlight**. It would be great if there was a way for users to also upload photos of their pets to accompany the descriptions.

**Comment by gabrysia694** [comment]
> Currently, users can only enter text descriptions of their pets in **MyPetSpotlight**. It would be great if there was a way for users to also upload photos of their pets to accompany the descriptions.

Great idea! Do you want to work on that?

**Comment by harisdev-netizen** [comment]
> > Currently, users can only enter text descriptions of their pets in **MyPetSpotlight**. It would be great if there was a way for users to also upload photos of their pets to accompany the descriptions.
> 
> Great idea! Do you want to work on that?

Sure, I will but within few days. Currently I have a lot on my plate. If no one worked on this then I will make sure to make PR.

**Comment by gabrysia694** [comment]
> > > Currently, users can only enter text descriptions of their pets in **MyPetSpotlight**. It would be great if there was a way for users to also upload photos of their pets to accompany the descriptions.
> > 
> > 
> > Great idea! Do you want to work on that?
> 
> Sure, I will but within few days. Currently I have a lot on my plate. If no one worked on this then I will make sure to make PR.

Sounds good. Good luck with whatever you're working on!

**Comment by harisdev-netizen** [comment]
> > > > Currently, users can only enter text descriptions of their pets in **MyPetSpotlight**. It would be great if there was a way for users to also upload photos of their pets to accompany the descriptions.
> > > 
> > > 
> > > Great idea! Do you want to work on that?
> > 
> > 
> > Sure, I will but within few days. Currently I have a lot on my plate. If no one worked on this then I will make sure to make PR.
> 
> Sounds good. Good luck with whatever you're working on!

Thank you @gabrysia694 and it's really nice working with you. I hope I will contribute more to your projects.

**Comment by gabrysia694** [comment]
> I think no one has worked on this issue. Assign it to me @gabrysia694, weekend is around and I'll work on this issue on weekend

Awesome, I'm assigning you right away. Take your time!

**Comment by harisdev-netizen** [comment]
> > I think no one has worked on this issue. Assign it to me @gabrysia694, weekend is around and I'll work on this issue on weekend
> 
> Awesome, I'm assigning you right away. Take your time!

Ping other contributors to add their pet images.

**Comment by harisdev-netizen** [comment]
Hey @gabrysia694 it'd be great if you could give me a testimonial on my [LinkFree](https://linkfree.io/harisdev-netizen) if that's fine with you.
