### ISSUE TITLE
Creating database

### ISSUE THREAD

**Issue by amike6** [gabrysia694/MyPetSpotlight#12]
@gabrysia694 I would like to be assigned a task where we make a form that takes the info from user and stores it in a database so it can be displayed as a card.

**Comment by gabrysia694** [comment]
> @gabrysia694 I would like to be assigned a task where we make a form that takes the info from user and stores it in a database so it can be displayed as a card.

Perfect, it's all yours then!

**Comment by gabrysia694** [comment]
hey @amike6, how is it going?

**Comment by mansir93** [comment]
I just organize the data in a file that can be use as database internal.

**Comment by Helixjoe** [comment]
Is the issue still open to work upon ?
