### ISSUE TITLE
Customizing "Add your pet!" Button

### ISSUE THREAD

**Issue by harisdev-netizen** [gabrysia694/MyPetSpotlight#17]
Currently, the "Add your pet" button on our website is very basic and doesn't stand out enough. As a result, users may not notice it or may have difficulty finding it. To improve the user experience, we want to customize the button using CSS to make it more visually appealing and prominent on the page. This will help users quickly identify where to go to add their pet, which will improve overall engagement with this feature.

**Comment by gabrysia694** [comment]
Good idea! Let's see if anyone is interested in working on that issue. If not, I'll take care of it soon :)

**Comment by harisdev-netizen** [comment]
> Good idea! Let's see if anyone is interested in working on that issue. If not, I'll take care of it soon :)

Perfecto

**Comment by amrit2611** [comment]
### Hey! I have some ideas and would love to work on this.

**Comment by gabrysia694** [comment]
> ### Hey! I have some ideas and would love to work on this.

Hey @amrit2611! This issue has just been solved but we've got some other ones, maybe you want to take look at them? :)

**Comment by amrit2611** [comment]
> > ### Hey! I have some ideas and would love to work on this.
> 
> Hey @amrit2611! This issue has just been solved but we've got some other ones, maybe you want to take look at them? :)

Sure !
