### ISSUE TITLE
Create footer for MyPetSpotlight

### ISSUE THREAD

**Issue by harisdev-netizen** [gabrysia694/MyPetSpotlight#21]
We need to create a footer for the MyPetSpotlight. The footer should also include social media icons to allow users to follow us on different platforms. The design of the footer should match the existing style of the website.

**Comment by gabrysia694** [comment]
Great idea, maybe someone will want to work on this :)

**Comment by harisdev-netizen** [comment]
> Great idea, maybe someone will want to work on this :)

Maybe or otherwise I am here with open hands to work on the enhancement 😂

**Comment by harisdev-netizen** [comment]
> > Great idea, maybe someone will want to work on this :)
> 
> Maybe or otherwise I am here with open hands to work on the enhancement 😂

**Comment by mmnldm** [comment]
Hello there, I would like to work on the footer!

**Comment by harisdev-netizen** [comment]
> Hello there, I would like to work on the footer!

@gabrysia694 assign the issue to @mmnldm

**Comment by amrit2611** [comment]
### I would love to work on this !

**Comment by gabrysia694** [comment]
@mmnldm you're assigned, take your time :)

**Comment by gabrysia694** [comment]
@amrit2611 would you like to contribute by adding your pet to our webiste? :) I'll ping you once we open any new issues!

**Comment by amrit2611** [comment]
> @amrit2611 would you like to contribute by adding your pet to our webiste? :) I'll ping you once we open any new issues!
<br>
@gabrysia694 <br>I'm actively looking for open issues to contribute to.<br> 
So do let me know, I would love to be a part of it.

**Comment by gabrysia694** [comment]
> > @amrit2611 would you like to contribute by adding your pet to our webiste? :) I'll ping you once we open any new issues!
> 
> 
> @gabrysia694
> I'm actively looking for open issues to contribute to.
> So do let me know, I would love to be a part of it.

I will! Feel free to check out issue #1 for now :)
