### ISSUE TITLE
Add pictures to the cards

### ISSUE THREAD

**Issue by gabrysia694** [gabrysia694/MyPetSpotlight#22]
We need to add some default animal pictures to the existing cards, and later on, pet owners who have already added their pets can choose to replace the default picture with a photo of their own furry friend. They will be all pinged once the change is made.

**Comment by Yashdon999** [comment]
I Want to Work on this issue

**Comment by Lalman888** [comment]
@gabrysia694  Is this issue resolved I want to work on this issue

**Comment by gabrysia694** [comment]
> @gabrysia694 Is this issue resolved I want to work on this issue

This issue has just been solved but take a look at issue #1, we'd love to have your pet's info on our website :)
