### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by its-your-invi** [gabrysia694/MyPetSpotlight#38]
One thing missing in the website interface is - a favicon. It can be "MyPetSpotlight" logo or any icon related to pets. It will enhance the website's visual appeal.

**Comment by gabrysia694** [comment]
Good idea, would you like to work on that?

**Comment by its-your-invi** [comment]
> Good idea, would you like to work on that?

Yeah Sure. But what will be the icon ?

**Comment by gabrysia694** [comment]
> > Good idea, would you like to work on that?
> 
> Yeah Sure. But what will be the icon ?

We don't have a logo so it could be an animal themed icon like a cat or a dog
