### ISSUE TITLE
[BUG] misaligned cards on Safari browser

### ISSUE THREAD

**Issue by gabrysia694** [gabrysia694/MyPetSpotlight#50]
![342809351_578447887449610_6039262296569712189_n](https://user-images.githubusercontent.com/97764356/236799458-6954cb4a-1293-4e66-87a2-08a3b0feba92.jpg)

Seems like the content of 3 cards moved to the very top of a page when displayed on Safari browser. I don't know what it looks like on desktop though.

**Comment by its-your-invi** [comment]
When the personality traits are less than three, a gap will be created between the img and top of the card. To remove this, I added js and made their position absolute. In Chrome, Edge they are positioned relative to the nearest positioned ancestor element. But in Safari they are positioned relative to the initial containing block body.
