### ISSUE TITLE
Request for Return to Top Button

### ISSUE THREAD

**Issue by harisdev-netizen** [gabrysia694/MyPetSpotlight#54]
I am requesting that a "Return to Top" button be added to the website. This would be a valuable addition because it would allow users to quickly return to the top of the page.

I suggest that the button be located in the bottom right corner of the page and be represented by an arrow pointing up. The button should be labeled "Back to Top", "Scroll to Top", "Up arrow" or "Up icon."

**Comment by AniketNS** [comment]
I'd like to work on that. Assign this to me @gabrysia694

**Comment by harisdev-netizen** [comment]
> Sounds like a good idea, would you like to work on that?

@gabrysia694 assign it to @AniketNS. I will work on some other issues. I already have like thousands of ideas for the project to implement. Haha

**Comment by gabrysia694** [comment]
I'm assigning it to you @AniketNS then :)

**Comment by AniketNS** [comment]
Okie, I'm on it
