### ISSUE TITLE
Adding Open Graph tags

### ISSUE THREAD

**Issue by gabrysia694** [gabrysia694/MyPetSpotlight#61]
We could add Open Graph tags to the website for better sharing on social media platforms such as Facebook or Twitter. These tags provide important information to these platforms and can improve the appearance of the website when it is shared.

**Comment by Ruby-Jain** [comment]
Hi, Can I work on this issue?

**Comment by gabrysia694** [comment]
Hey, of course! I'll assign it to you right away

**Comment by Helixjoe** [comment]
Can I work on this ?

**Comment by gabrysia694** [comment]
> Can I work on this ?

of course! I'll assign it to you

**Comment by Helixjoe** [comment]
Made a PR (Open Graph Tags added to index.html #67), kindly review it
