### ISSUE TITLE
Implementing Pagination

### ISSUE THREAD

**Issue by Frenziecodes** [gabrysia694/MyPetSpotlight#69]
Hey @gabrysia694!

I hope you're doing well. I wanted to share a suggestion with you to enhance your platform's user interface. Have you considered using pagination?

Pagination can make a big difference in terms of performance and user experience. By breaking down the content into smaller, easily manageable chunks, you can optimize the loading speed of your platform. This means users won't have to wait for a long time for everything to load at once.

Another benefit of pagination is that it reduces cognitive load. When the interface is too long, it can be overwhelming for users to find the information they need. By dividing the content into smaller sections, users can focus on one part at a time, making it easier for them to locate specific information.

I believe that implementing pagination could significantly improve the overall usability of your platform. Let me know if you have any questions or need further clarification.

Thanks for considering this suggestion!

**Comment by its-your-invi** [comment]
As the pet cards are the main content of this website and we want users to be able to easily view and interact with all the pet cards, adding pagination may not be the best approach. I suggest we consider the following options as alternative to the idea of adding pagination :

- _**Infinite Scrolling**_: Picture a mesmerizing experience where the pet feed gracefully unfolds as users scroll, providing a seamless journey through a captivating assortment of adorable companions.

- _**Different Pet Sections**_: Let's embark on a journey of organization and convenience by dividing our pets into distinct sections such as Dogs, Cats, Fish, Hamsters, Birds, and more. This arrangement will allow users to effortlessly explore their favorite pet categories with a touch of elegance.

- _**Adding a Load More Button**_: Unveil a touch of whimsy by introducing a "Load More" button that beckons users to uncover more delightful Pet Cards at their own pace. Each click opens a world of furry wonders, ensuring a captivating experience.

These alternatives possess the potential to elevate user engagement and create a delightful ambiance. I look forward to hearing your thoughts and preferences regarding the path we should pursue for an enhanced user experience.

**Comment by gabrysia694** [comment]
Different pet sections is an awesome idea, we could make three buttons presented on the home page which redirect the user to another page with selected animals. I suggest we stick to Cats, Dogs and Others since I doubt there's gonna be enough fish or birds to make separate pages for them.

**Comment by its-your-invi** [comment]
Rather than redirect a user we can make a Pet Section just after the slideshow in the same webpage like these : 

![image](https://github.com/gabrysia694/MyPetSpotlight/assets/95538354/7e5c5c23-c58d-4f0f-92d6-4057e37cb366)


![image](https://github.com/gabrysia694/MyPetSpotlight/assets/95538354/adeba062-003b-43cf-8c50-ba1dc12ffb49)


![image](https://github.com/gabrysia694/MyPetSpotlight/assets/95538354/91616554-43df-4e13-8b5d-6b792da88842)


![image](https://github.com/gabrysia694/MyPetSpotlight/assets/95538354/8c7956ed-6ff3-40cb-84b3-a1964729de34)

**Comment by gabrysia694** [comment]
> Rather than redirect a user we can make a Pet Section just after the slideshow in the same webpage like these :
> 
> ![image](https://user-images.githubusercontent.com/95538354/241419999-7e5c5c23-c58d-4f0f-92d6-4057e37cb366.png)
> 
> ![image](https://user-images.githubusercontent.com/95538354/241419786-adeba062-003b-43cf-8c50-ba1dc12ffb49.png)
> 
> ![image](https://user-images.githubusercontent.com/95538354/241419813-91616554-43df-4e13-8b5d-6b792da88842.png)
> 
> ![image](https://user-images.githubusercontent.com/95538354/241419833-8c7956ed-6ff3-40cb-84b3-a1964729de34.png)

looks like a great solution!

**Comment by its-your-invi** [comment]
> looks like a great solution!

Should I submit a PR ?

**Comment by its-your-invi** [comment]
> looks like a great solution!

Should I submit a PR ?

**Comment by gabrysia694** [comment]
> > looks like a great solution!
> 
> Should I submit a PR ?

yes, please do
